# Generated by Django 2.2 on 2020-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200729_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='nmorv', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='kpiqe', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='address1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='address2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
