# Generated by Django 2.2 on 2020-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200803_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product_list',
            name='offer_Id',
        ),
        migrations.AddField(
            model_name='order_product_list',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='oksqx', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='mnhkh', max_length=100, unique=True),
        ),
    ]
