# Generated by Django 2.2 on 2020-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200804_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='shgqh', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='qwnom', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('wallet', 'wallet'), ('cod', 'cod'), ('debit_card', 'debit_card'), ('credit_card', 'credit_card')], max_length=20, null=True),
        ),
    ]
