# Generated by Django 2.2 on 2020-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20200805_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='bpoee', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='gmsye', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='UserProfileImages/'),
        ),
    ]
