# Generated by Django 2.2 on 2020-08-06 04:48

import dashboard.productModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20200805_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='klgbk', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='YLLED', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category_id',
            field=models.IntegerField(blank=True, default=dashboard.productModel.randomNo),
        ),
    ]
