# Generated by Django 2.2 on 2020-08-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200806_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='wgvlk', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='FDTDN', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='wallet_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
