# Generated by Django 2.2 on 2020-08-13 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0044_auto_20200812_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='njoar', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Product_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='AFZFQ', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Product_Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('subscription_price', models.FloatField(null=True)),
                ('schedule_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Alternate Day', 'Alternate Day'), ('Every 3 days', 'Every 3 days'), ('Weekly', 'Weekly')], max_length=30, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('delete_subscription_reason', models.CharField(blank=True, choices=[('Quality issue', 'Quality issue'), ('Delivery is always late', 'Delivery is always late'), ('Bill issue', 'Bill issue'), ('Changing product', 'Changing product'), ('Moving out of society', 'Moving out of society'), ('Irregular deliveries', 'Irregular deliveries'), ('Bag not received', 'Bag not received'), ('Issue with customer care', 'Issue with customer care'), ('Other', 'Other')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_dashboard_product_subscribe_related', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.RegisterUser')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_dashboard_product_subscribe_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_Subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Product_Subscribe'),
        ),
    ]
