# Generated by Django 2.2 on 2020-08-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20200813_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_Subscribe',
        ),
        migrations.RemoveField(
            model_name='product_subscribe',
            name='subscription_price',
        ),
        migrations.AddField(
            model_name='product_subscribe',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='dikyw', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='PLTTX', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscribe',
            name='delete_subscription_reason',
            field=models.CharField(blank=True, choices=[('Delivery is always late', 'Delivery is always late'), ('Bill issue', 'Bill issue'), ('Changing product', 'Changing product'), ('Moving out of society', 'Moving out of society'), ('Irregular deliveries', 'Irregular deliveries'), ('Bag not received', 'Bag not received'), ('Issue with customer care', 'Issue with customer care'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
