# Generated by Django 2.2 on 2020-08-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20200816_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discountCouponCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='hhlbj', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='WZYNZ', max_length=100, unique=True),
        ),
    ]
