# Generated by Django 2.2 on 2020-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20200818_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='irkmj', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='SJDZB', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscribe',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_subscribe',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
