# Generated by Django 2.2 on 2020-08-22 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20200818_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='tbbsv', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='WEBMK', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator(message="Email Id must be entered in the format: example326@gmail.com' Up to 50 character allowed.", regex='^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$')]),
        ),
    ]
