# Generated by Django 2.2 on 2020-08-29 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20200824_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='ewayu', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='FUHFX', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(blank=True, db_column='product_images', null=True, upload_to='productImages/'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='mob_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999',0989279999 Up to 14 digits allowed.", regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
    ]
