# Generated by Django 2.2 on 2020-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20200829_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='dxlel', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='TSLJT', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to='productImages/'),
        ),
    ]
