# Generated by Django 2.2 on 2020-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20200831_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='lvnvt', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ordertrackstatus',
            name='orderTrackStatus_id',
            field=models.CharField(blank=True, default='xjawp', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default='QIHUX', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.FileField(blank=True, db_column='product_images', null=True, upload_to='productImages/'),
        ),
    ]
